-- CREATE DATABASE IF NOT EXISTS user-service;
CREATE DATABASE IF NOT EXISTS `product-service`;
CREATE DATABASE IF NOT EXISTS `order-service`;
CREATE DATABASE IF NOT EXISTS `inventory-service`;
-- CREATE DATABASE IF NOT EXISTS payment-service;
-- CREATE DATABASE IF NOT EXISTS notification-service;
